apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres # Change this path to a directory on the node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "root"
            - name: POSTGRES_DB
              value: "debt_solver"
            - name: DB_SSLMODE
              value: "disable"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432 # Port to expose within the cluster
      targetPort: 5432 # Port the pod container listens on

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: billzhaohongwei/caa900debtsolverproject-auth-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres-service" # Name of the PostgreSQL service
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "root"
            - name: DB_NAME
              value: "debt_solver"
            - name: DB_SSLMODE
              value: "disable"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000 # Optional, or Kubernetes assigns one
  type: NodePort
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-service-deployment
  labels:
    app: expense-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-service
  template:
    metadata:
      labels:
        app: expense-service
    spec:
      containers:
        - name: expense-service
          image: billzhaohongwei/caa900debtsolverproject-expense-mgmt:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: "postgres-service" # PostgreSQL service name
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "root"
            - name: DB_NAME
              value: "debt_solver"
            - name: DB_SSLMODE
              value: "disable"

---
apiVersion: v1
kind: Service
metadata:
  name: expense-service
spec:
  selector:
    app: expense-service
  ports:
    - protocol: TCP
      port: 8081       # ClusterIP port
      targetPort: 8081 # Container port
      nodePort: 30001  # Exposed NodePort
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport-service
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432       # The port exposed within the cluster
      targetPort: 5432 # The port the PostgreSQL container listens on
      nodePort: 30003  # The NodePort exposed to the host machine
  type: NodePort