name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17' # Use the appropriate Go version

      # Build the Go project (optional if Dockerfile handles it)
      - name: Build Go project
        run: |
          go mod download
          go build -o app

      # Log in to the container registry
      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t myregistry/my-backend-app:${{ github.sha }} .

      # Push Docker image to registry
      - name: Push Docker image
        run: |
          docker push myregistry/my-backend-app:${{ github.sha }}
