name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
        go-version: '1.17' # Use the appropriate Go version
        
      # Build the Go project (optional if Dockerfile handles it)
      - name: Build Go project
        run: |
          go mod download
          go build -o app
