name: "Deploy Infrastructure and Kubernetes Resources"

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  terraform:
    name: "Terraform and Kubernetes Deployment"
    runs-on: ubuntu-latest

    env:  # Set environment variables for both Terraform and Azure provider
      ARM_CLIENT_ID: ${{ secrets.TF_VAR_agent_client_id }}
      ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_agent_client_secret }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_subscription_id }}
      ARM_TENANT_ID: ${{ secrets.TF_VAR_tenant_id }}
      TF_VAR_agent_client_id: ${{ secrets.TF_VAR_agent_client_id }}
      TF_VAR_agent_client_secret: ${{ secrets.TF_VAR_agent_client_secret }}
      TF_VAR_subscription_id: ${{ secrets.TF_VAR_subscription_id }}
      TF_VAR_tenant_id: ${{ secrets.TF_VAR_tenant_id }}

    steps:
      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

    # Create SSH Public Key File
      - name: Create SSH Public Key File
        run: |
            echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > a1
            chmod 600 a1
            ssh-keygen -y -f a1 > a1.pub

      # Set Up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Terraform Commands
      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Extract Kind VM Public IP
      - name: Extract Kind VM Public IP
        id: extract_ip
        run: |
          KIND_PUBLIC_IP=$(terraform output -raw kind_public_ip)
          echo "::set-output name=kind_vm_ip::$KIND_PUBLIC_IP"
        shell: bash

      # Wait for VM to be Ready
      - name: Wait for VM to be Ready
        run: |
          echo "Waiting for the Kind VM to be ready..."
          for i in {1..15}; do
            nc -zv ${{ steps.extract_ip.outputs.kind_vm_ip }} 22 && break || sleep 10
          done

      # Configure SSH Key
      - name: Configure SSH Key
        run: |
          echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Copy Kubernetes Manifest to VM
      - name: Copy Kubernetes Manifest
        run: |
          scp -i ~/.ssh/id_rsa application.yaml azureuser@${{ steps.extract_ip.outputs.kind_vm_ip }}:/home/azureuser/

      # Apply Kubernetes Manifest on VM
      - name: Apply Kubernetes Manifest
        run: |
          ssh -i ~/.ssh/id_rsa azureuser@${{ steps.extract_ip.outputs.kind_vm_ip }} kubectl apply -f /home/azureuser/application.yaml