name: Terraform Destroy

on:
  workflow_dispatch: # Allows manual trigger
#  pull_request:
#    branches:
#      - main
#  push:
#    branches:
#      - destroy

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
